# Generated by Django 5.2.4 on 2025-11-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('pest_name', models.CharField(max_length=200)),
                ('disease_name', models.CharField(blank=True, max_length=200)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('min_humidity', models.FloatField(blank=True, null=True)),
                ('max_humidity', models.FloatField(blank=True, null=True)),
                ('rainfall_condition', models.CharField(blank=True, max_length=50)),
                ('symptoms', models.TextField()),
                ('prevention', models.TextField()),
                ('treatment', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
            ],
        ),
    ]
